config/routes.rb
Movie::Application.routes.draw do
  get "film/index"
  get "film/new"
  post "film/create"
  get "/", :to => 'static#home'
  get "/about", :to => 'static#about'

end

app/models/film.rb
class Film < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/film_controller.rb
class FilmController < ApplicationController
  def index
    @films = Film.all()
  end

  def new
  end

  def create
    @film = Film.new(post_params)
    
    @film.save
    redirect_to film_index_path
  end
  
  
   private 
    def post_params
      params.require(:film).permit(:title, :year, :actors, :description)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/film_helper.rb
module FilmHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/film/create.html.erb
<h1>Film#create</h1>
<p>Find me in app/views/film/create.html.erb</p>

app/views/film/index.html.erb
<h1>Your Movies</h1>

<% @films.each do |film| %>
  <%= film.title %><br>
  <%= film.year %><br>
  <%= film.actors %><br>
  <%= film.description %><br>
<% end %>

app/views/film/new.html.erb
<h1>Add Movies</h1>

<%= form_for :film, url: film_create_path do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  
   <p>
    <%= f.label :year %>
    <%= f.text_field :year %>
  </p>
  
   <p>
    <%= f.label :actors %>
    <%= f.text_field :actors %>
  </p>
  
   <p>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </p>
  
  <p>
    <%= f.submit 'submit' %>
  </p>
  

  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">
</head>
 
<body>
 
<!-- PART 3 - ROWS AND COLUMNS -->
    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            <li><a href="/about">About</a></li>
            <li><a href="/film/new">New</a></li>
            <li><a href="/film/index">Index</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
 
 
<!-- PART 1 - THE JUMBOTRON -->
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>Favorite Movies</h1>
      </div>
    </div>
 
    
<%= yield %>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
 
    <!-- Latest compiled and minified JavaScript -->
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
</body>
 
</html>